/**
 * @file Content collections — the single source of truth for site content.
 * @module content.config
 */
import { defineCollection } from 'astro:content';
import { file } from 'astro/loaders';
import { z } from 'astro/zod';
import yaml from 'js-yaml';

// Generated by scripts/sync-projects.mjs from your pinned GitHub repos.
// Don't edit by hand — changes are overwritten on the next sync.
const projects = defineCollection({
  loader: file('src/data/projects.json'),
  schema: z.object({
    name: z.string(),
    github: z.url().optional(),
    demo: z.url().optional(),
    tech: z.array(z.string()),
    status: z.string(),
    summary: z.string(),
    whyItMatters: z.string().optional(),
    readmeSha: z.string().nullable(),
    order: z.number(),
  }),
});

// Hand-written corrections, keyed by GitHub repo name. Every field is optional
// and wins over the generated value.
const projectOverrides = defineCollection({
  // A file with only comments parses to nothing; treat it as "no overrides".
  loader: file('src/data/overrides.yml', { parser: (text) => yaml.load(text) ?? {} }),
  schema: z.object({
    name: z.string().optional(),
    demo: z.url().optional(),
    tech: z.array(z.string()).optional(),
    status: z.string().optional(),
    summary: z.string().optional(),
    whyItMatters: z.string().optional(),
    order: z.number().optional(),
    hidden: z.boolean().default(false),
  }),
});

export const collections = { projects, projectOverrides };
